---
name: PR

on:
  pull_request:

jobs:
  LintAndBuild:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ['1.22.x']
    steps:
      - name: Check conventional commits in PR
        uses: Namchee/conventional-pr@v0.13.0
        with:
          access_token: ${{ secrets.github_token }}
          close: false
          strict: false
          title_pattern: '([fix|enh|feat|ci|chore|docs\-]+)(\([\w\-]+\))?!?: [A-Z][\w\s:\-]+'
          commit_pattern: '([fix|enh|feat|ci|chore|docs\-]+)(\([\w\-]+\))?!?: [A-Z][\w\s:\-]+'

      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Lint
        uses: reviewdog/action-golangci-lint@v2.3.3
        with:
          github_token: ${{ secrets.github_token }}
          golangci_lint_flags: "--config=.golangci.yml"
          fail_on_error: true

      - name: Setup env
        run: |
          echo "GOPATH=$(dirname $GITHUB_WORKSPACE)" >> $GITHUB_ENV
          echo "$(dirname $GITHUB_WORKSPACE)/bin" >> $GITHUB_PATH
          mkdir -p "$(dirname $GITHUB_WORKSPACE)/src/github.com/nonstdout"
          ln -sf "$GITHUB_WORKSPACE/" "$(dirname $GITHUB_WORKSPACE)/src/github.com/nonstdout/terraform-provider-netbox"
        shell: bash

      - name: Go installation
        uses: actions/setup-go@v4.0.1
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: |
          cd "$(dirname $GITHUB_WORKSPACE)/src/github.com/nonstdout/terraform-provider-netbox"
          make build
        shell: bash
